In [3]:
import numpy as np

In [6]:
a = [1,2,3]
b = [4,5,6]

In [12]:
a

[1, 2, 3]

In [9]:
a+b

[1, 2, 3, 4, 5, 6]

In [10]:
arr1 = np.array(a)
arr2 = np.array(b)

In [11]:
arr1

array([1, 2, 3])

In [14]:
arr1+ arr2

array([5, 7, 9])

In [16]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [18]:
3*arr1

array([3, 6, 9])

In [19]:
arr1.shape

(3,)

In [20]:
arr1

array([1, 2, 3])

In [22]:
arr = np.array([[1,2,3]])

In [24]:
arr.shape

(1, 3)

In [26]:
3*arr

array([[3, 6, 9]])

In [42]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [43]:
arr1.shape

(3, 3)

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr1[1, 1]

5

In [47]:
arr1[  : 2 ,  : ]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr1 [ [0,2] , 1:3  ]

array([[2, 3],
       [8, 9]])

In [53]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
9 * arr1

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [58]:
#  element wise multiplication
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [60]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2

array([4, 5, 6])

In [62]:
#  dot product
np.dot(arr1, arr2)

array([ 32,  77, 122])

In [64]:
p_A = np.array([0,1]) 
p_B = np.array([6,5]) 

In [69]:
def distance(p_A, p_B):
    return np.sqrt(np.sum((p_B - p_A)**2))

In [79]:
np.random.randint(-10, 100, size = (3,3))

array([[-7,  8, 30],
       [87, 94, 40],
       [40,  1, -4]])

In [82]:
np.sin(180)

-0.8011526357338306

In [85]:
arr

array([[1, 2, 3]])

In [86]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
#  BroadCasting
arr + arr1

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [90]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])